[package]
name = "stark-squeeze"
version = "0.1.0"
edition = "2021"

[dependencies]
indicatif = "0.17.11"
serde_json = "1.0.140"
phf = { version = "0.11", features = ["macros"] }
dialoguer = "0.11"
colored = "2.0"
serde = { version = "1.0", features = ["derive"] }
# StarkNet interaction
starknet = "0.9" # Or latest available version

# Async runtime
tokio = { version = "1.0", features = ["full"] }

# Hashing for upload IDs
blake3 = "1.3"
url = "2.5.4"
clap = { version = "4.5.37", features = ["derive"] }


